name: hyperpay_flutter
description: A Flutter plugin for HyperPay payment gateway with enhanced features including Apple Pay and card payments. Created by Sahibzada Arham Anwaar Bugvi.
version: 0.1.0+1
repository: https://github.com/iarhamanwaar/hyperpay_flutter
homepage: https://github.com/iarhamanwaar/hyperpay_flutter

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.7.1
  mocktail: ^1.0.4
  very_good_analysis: ">=6.0.0 <8.0.0"

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: HyperPayHandler
      android:
        package: com.bugvi.hyperpay_flutter
        pluginClass: HyperpayFlutterPlugin
