blank_issues_enabled: false
contact_links:
  - name: Bug Report
    url: https://github.com/iarhamanwaar/hyperpay_flutter/issues/new?template=bug_report.md
    about: File a bug report
  - name: Feature Request
    url: https://github.com/iarhamanwaar/hyperpay_flutter/issues/new?template=feature_request.md
    about: Request a new feature
  - name: Question
    url: https://github.com/iarhamanwaar/hyperpay_flutter/discussions
    about: Ask a question or discuss the project